export enum SubSituacao {
  CRISE = 'CRISE',
  TRANSICAO = 'TRANSICAO',
  INTERACAO_SOCIAL = 'INTERACAO_SOCIAL',
  ESTEREOTIPIA = 'ESTEREOTIPIA',
  AGRESSIVIDADE = 'AGRESSIVIDADE',
  FUGA = 'FUGA',
  ALIMENTACAO = 'ALIMENTACAO'
}
